In [0]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf
import keras as kr
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [0]:
data = pd.read_csv('/content/Churn_Modelling.csv')
print(data.head())

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]


In [0]:
X = data.iloc[:, 3:13].values

In [0]:
y = data.iloc[:, 13].values

In [0]:
print(X)
print(y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


In [0]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
print(X[:,1])
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
print(X[:,2])
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]
print(X)


[0 2 0 ... 0 1 0]
[0 0 0 ... 0 1 0]
[[0.0000000e+00 0.0000000e+00 6.1900000e+02 ... 1.0000000e+00
  1.0000000e+00 1.0134888e+05]
 [0.0000000e+00 1.0000000e+00 6.0800000e+02 ... 0.0000000e+00
  1.0000000e+00 1.1254258e+05]
 [0.0000000e+00 0.0000000e+00 5.0200000e+02 ... 1.0000000e+00
  0.0000000e+00 1.1393157e+05]
 ...
 [0.0000000e+00 0.0000000e+00 7.0900000e+02 ... 0.0000000e+00
  1.0000000e+00 4.2085580e+04]
 [1.0000000e+00 0.0000000e+00 7.7200000e+02 ... 1.0000000e+00
  0.0000000e+00 9.2888520e+04]
 [0.0000000e+00 0.0000000e+00 7.9200000e+02 ... 1.0000000e+00
  0.0000000e+00 3.8190780e+04]]


/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [0]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
# print('Initial Train: ',X_train)
X_train = sc.fit_transform(X_train)
# print('Trnasformed Train: ',X_train)
print('Inital Test:',X_test)
X_test = sc.transform(X_test)
print('Transformed Test:',X_test)

Inital Test: [[1.0000000e+00 0.0000000e+00 5.9700000e+02 ... 1.0000000e+00
  1.0000000e+00 1.9285267e+05]
 [0.0000000e+00 0.0000000e+00 5.2300000e+02 ... 1.0000000e+00
  0.0000000e+00 1.2870210e+05]
 [0.0000000e+00 1.0000000e+00 7.0600000e+02 ... 1.0000000e+00
  1.0000000e+00 7.5732250e+04]
 ...
 [0.0000000e+00 1.0000000e+00 5.7800000e+02 ... 1.0000000e+00
  0.0000000e+00 1.4153319e+05]
 [1.0000000e+00 0.0000000e+00 6.5000000e+02 ... 1.0000000e+00
  1.0000000e+00 1.1276480e+04]
 [1.0000000e+00 0.0000000e+00 5.7300000e+02 ... 1.0000000e+00
  0.0000000e+00 1.9295060e+05]]
Transformed Test: [[ 1.75486502 -0.57369368 -0.55204276 ...  0.64259497  0.9687384
   1.61085707]
 [-0.5698444  -0.57369368 -1.31490297 ...  0.64259497 -1.03227043
   0.49587037]
 [-0.5698444   1.74309049  0.57162971 ...  0.64259497  0.9687384
  -0.42478674]
 ...
 [-0.5698444   1.74309049 -0.74791227 ...  0.64259497 -1.03227043
   0.71888467]
 [ 1.75486502 -0.57369368 -0.00566991 ...  0.64259497  0.9687384
  -1.54507805

In [0]:
classifier = Sequential()
# Layer 1
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu', input_dim = 11))

# Layer 2
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu'))

# Output Layer
classifier.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))

W0827 19:38:46.637230 139683225782144 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until
W0827 19:38:46.663094 139683225782144 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0827 19:38:46.667533 139683225782144 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.



In [0]:
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

W0827 19:38:48.882225 139683225782144 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0827 19:38:48.914473 139683225782144 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:3376: The name tf.log is deprecated. Please use tf.math.log instead.

W0827 19:38:48.921202 139683225782144 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/nn_impl.py:180: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [0]:
classifier.fit(X_train, y_train, batch_size = 10, nb_epoch = 50)

Epoch 1/50
1290/8000 [===>..........................] - ETA: 0s - loss: 0.4067 - acc: 0.8341

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


8000/8000 [==============================] - 1s 112us/step - loss: 0.3985 - acc: 0.8371
Epoch 2/50
8000/8000 [==============================] - 1s 117us/step - loss: 0.3981 - acc: 0.8376
Epoch 3/50
8000/8000 [==============================] - 1s 117us/step - loss: 0.3975 - acc: 0.8375
Epoch 4/50
8000/8000 [==============================] - 1s 115us/step - loss: 0.3975 - acc: 0.8372
Epoch 5/50
8000/8000 [==============================] - 1s 112us/step - loss: 0.3970 - acc: 0.8381
Epoch 6/50
8000/8000 [==============================] - 1s 114us/step - loss: 0.3967 - acc: 0.8372
Epoch 7/50
8000/8000 [==============================] - 1s 117us/step - loss: 0.3966 - acc: 0.8377
Epoch 8/50
8000/8000 [==============================] - 1s 114us/step - loss: 0.3964 - acc: 0.8371
Epoch 9/50
8000/8000 [==============================] - 1s 118us/step - loss: 0.3961 - acc: 0.8375
Epoch 10/50
8000/8000 [==============================] - 1s 121us/step - loss: 0.3956 - acc: 0.8381
Epoch 11/50
8000/800

In [0]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)
print(y_pred)

[[False]
 [False]
 [False]
 ...
 [False]
 [False]
 [False]]


In [0]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)


[[1548   47]
 [ 234  171]]
